sec = {  # Security
    1102: {"Descr": "The audit log was cleared",
           "Provider": "Microsoft-Windows-Eventlog",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId"},

    4616: {"Descr": "The system time was changed",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "PreviousTime": "PreviousTime",
           "NewTime": "NewTime",
           "ProcessId": "ProcessId",  # Win 7+
           "ProcessName": "ProcessPath"},  # Win 7+

    4624: {"Descr": "An account was successfully logged on",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "TargetUserSid": "TargetSID",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain",
           "TargetLogonId": "TargetLogonId",
           "LogonType": "+LogonType",
           "WorkstationName": "WorkstationName",
           "LogonGuid": "LogonGUID",
           "TransmittedServices": "TransmittedServices",
           "IpAddress": "IP",
           "IpPort": "Port",
           "ProcessId": "ProcessId",
           "ProcessName": "ProcessPath",
           "AuthenticationPackageName": "AuthenticationPackage",
           "LogonProcessName": "LogonProcess",
           "KeyLength": "KeyLength",
           "RestrictedAdminMode": "RestrictedAdminMode",  # Win 10+
           "ElevatedToken": "ElevatedToken",  # Win 10+
           "TargetOutboundUserName": "TargetOutboundUsername",
           "TargetOutboundDomainName": "TargetOutboundDomain"},

    4625: {"Descr": "An account failed to log on",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "TargetUserSid": "TargetSID",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain",
           "LogonType": "+LogonType",
           "WorkstationName": "WorkstationName",
           "IpAddress": "IP",
           "IpPort": "Port",
           "LogonProcessName": "LogonProcessName",
           "Status": "+Status",
           "FailureReason": "FailureReason",  # %% format
           "SubStatus": "SubStatus",
           "ProcessId": "ProcessId",
           "ProcessName": "ProcessPath"},

    4627: {"Descr": "Group membership information",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "TargetUserSid": "TargetSID",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain",
           "LogonType": "+LogonType",
           "GroupMembership": "GroupMembership"},  # to convert

    4634: {"Descr": "An account was logged off",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "TargetUserSid": "TargetSID",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain",
           "TargetLogonId": "TargetLogonId",
           "LogonType": "+LogonType"},

    4647: {"Descr": "User initiated logoff",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "TargetUserSid": "TargetSID",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain",
           "TargetLogonId": "TargetLogonId"},

    4648: {"Descr": "A logon was attempted using explicit credentials",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "LogonGuid": "LogonGUID",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain",
           "TargetLogonGuid": "TargetLogonGuid",
           "TargetServerName": "TargetServerName",
           "TargetInfo": "TargetInfo",
           "IpAddress": "IP",
           "IpPort": "Port",
           "ProcessId": "ProcessId",
           "ProcessName": "ProcessPath"},

    4657: {"Descr": "A registry value was modified",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "ObjectName": "RegKey",
           "ObjectValueName": "RegValue",
           "OperationType": "OperationType",
           "OldValueType": "OldValueType",
           "OldValue": "OldValue",
           "NewValueType": "NewValueType",
           "NewValue": "NewValue",
           "ProcessId": "ProcessId",
           "ProcessName": "ProcessPath"},

    4661: {"Descr": "A handle to an object was requested",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "ObjectServer": "ObjectServer",
           "ObjectType": "ObjectType",
           "ObjectName": "ObjectName",
           "HandleId": "HandleId",
           "TransactionId": "TransactionId",
           "AccessList": "AccessList",  # %% format
           "AccessMask": "AccessMask",  # alternate representation of AccessList
           "PrivilegeList": "PrivilegeList",
           "Properties": "Properties",
           "RestrictedSidCount": "RestrictedSidCount",
           "ProcessId": "ProcessId",
           "ProcessName": "ProcessPath"},

    4662: {"Descr": "An operation was performed on an object",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "ObjectServer": "ObjectServer",
           "ObjectType": "ObjectType",
           "ObjectName": "ObjectName",
           "OperationType": "OperationType",
           "HandleId": "HandleId",
           "AccessList": "AccessList",  # %% format
           "AccessMask": "AccessMask",  # alternate representation of AccessList
           "Properties": "Properties"},

    4663: {"Descr": "An attempt was made to access an object",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "ObjectServer": "ObjectServer",
           "ObjectType": "ObjectType",
           "ObjectName": "ObjectName",
           "HandleId": "HandleId",
           "AccessList": "AccessList",  # %% format
           "AccessMask": "AccessMask",  # alternate representation of AccessList
           "ProcessId": "ProcessId",
           "ProcessName": "ProcessPath",
           "ResourceAttributes": "ResourceAttributes"},

    4672: {"Descr": "Special privileges assigned to new logon",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "TargetSID",
           "SubjectUserName": "TargetUsername",
           "SubjectDomainName": "TargetDomain",
           "SubjectLogonId": "TargetLogonId",
           "PrivilegeList": "PrivilegeList"},

    4673: {"Descr": "A privileged service was called",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "ObjectServer": "ObjectServer",
           "Service": "Service",
           "PrivilegeList": "PrivilegeList",
           "ProcessId": "ProcessId",
           "ProcessName": "ProcessPath"},

    4688: {"Descr": "A new process has been created",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "NewProcessId": "NewProcessId",
           "NewProcessName": "NewProcessPath",
           "TokenElevationType": "TokenElevationType",  # %% format
           "CommandLine": "Command",  # Win 8.1+
           "ProcessId": "ProcessId",
           # Win 10+
           "ParentProcessName": "ProcessPath",
           "MandatoryLabel": "+MandatoryLabel",
           "TargetUserSid": "TargetSID",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain",
           "TargetLogonId": "TargetLogonId"},

    4697: {"Descr": "A service was installed in the system",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "ServiceName": "ServiceName",
           "ServiceFileName": "ServicePath",
           "ServiceType": "+ServiceType",
           "ServiceStartType": "+ServiceStartType",
           "ServiceAccount": "Username"},

    4698: {"Descr": "A scheduled task was created",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "TaskName": "TaskName",
           "TaskContent": "TaskContent"},

    4699: {"Descr": "A scheduled task was deleted",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "TaskName": "TaskName",
           "TaskContent": "TaskContent"},

    4700: {"Descr": "A scheduled task was enabled",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "TaskName": "TaskName",
           "TaskContent": "TaskContent"},

    4701: {"Descr": "A scheduled task was disabled",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "TaskName": "TaskName",
           "TaskContent": "TaskContent"},

    4702: {"Descr": "A scheduled task was updated",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "TaskName": "TaskName",
           "TaskContentNew": "TaskContent"},

    4719: {"Descr": "System audit policy was changed",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "CategoryId": "CategoryId",  # %% format
           "SubcategoryId": "SubcategoryId",  # %% format
           "SubcategoryGuid": "SubcategoryGuid",  # %% format
           "AuditPolicyChanges": "AuditPolicyChanges"},  # %% format (multiple, joined with ', ')

    4720: {"Descr": "A user account was created",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "TargetUserSid": "TargetSID",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain",
           "PrivilegeList": "PrivilegeList",
           "SamAccountName": "SamAccountName",
           "DisplayName": "DisplayName",
           "UserPrincipalName": "UserPrincipalName",
           "HomeDirectory": "HomeDirectory",
           "HomePath": "HomePath",
           "ScriptPath": "ScriptPath",
           "ProfilePath": "ProfilePath",
           "UserWorkstations": "UserWorkstations",
           "PasswordLastSet": "PasswordLastSet",
           "AccountExpires": "AccountExpires",
           "PrimaryGroupId": "PrimaryGroupId",
           "AllowedToDelegateTo": "AllowedToDelegateTo",
           "OldUacValue": "OldUacValue",
           "SidHistory": "SIDHistory",
           "LogonHours": "LogonHours",
           "UserAccountControl": "UserAccountControl"},  # %% format (multiple, joined with ' ')

    4726: {"Descr": "A user account was deleted",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "TargetUserSid": "TargetSID",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain"},

    4728: {"Descr": "A member was added to a security-enabled global group",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "MemberSid": "TargetSID",
           "MemberName": "TargetUsername",
           "TargetSid": "TargetGroupSID",
           "TargetUserName": "TargetGroup",
           "TargetDomainName": "TargetDomain",
           "PrivilegeList": "PrivilegeList"},

    4732: {"Descr": "A member was added to a security-enabled local group",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "MemberSid": "TargetSID",
           "MemberName": "TargetUsername",
           "TargetSid": "TargetGroupSID",
           "TargetUserName": "TargetGroup",
           "TargetDomainName": "TargetDomain",
           "PrivilegeList": "PrivilegeList"},

    4738: {"Descr": "A user account was changed",  # non-changed values are -
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "TargetSid": "TargetSID",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain",
           "PrivilegeList": "PrivilegeList",
           "SamAccountName": "SamAccountName",
           "DisplayName": "DisplayName",
           "UserPrincipalName": "UserPrincipalName",
           "HomeDirectory": "HomeDirectory",
           "HomePath": "HomePath",
           "ScriptPath": "ScriptPath",
           "ProfilePath": "ProfilePath",
           "UserWorkstations": "UserWorkstations",
           "PasswordLastSet": "PasswordLastSet",
           "AccountExpires": "AccountExpires",
           "PrimaryGroupId": "PrimaryGroupId",
           "AllowedToDelegateTo": "AllowedToDelegateTo",
           "OldUacValue": "OldUacValue",  # to convert
           "NewUacValue": "NewUacValue",  # to convert
           "UserParameters": "UserParameters",
           "SidHistory": "SIDHistory",
           "LogonHours": "LogonHours",
           "UserAccountControl": "UserAccountControl"},  # %% format

    4740: {"Descr": "A user account was locked out",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "TargetSid": "TargetSID",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain"},

    4741: {"Descr": "A computer account was created",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "TargetSid": "TargetSID",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain",
           "PrivilegeList": "PrivilegeList",
           "SamAccountName": "SamAccountName",
           "DisplayName": "DisplayName",
           "UserPrincipalName": "UserPrincipalName",
           "HomeDirectory": "HomeDirectory",
           "HomePath": "HomePath",
           "ScriptPath": "ScriptPath",
           "ProfilePath": "ProfilePath",
           "UserWorkstations": "UserWorkstations",
           "PasswordLastSet": "PasswordLastSet",
           "AccountExpires": "AccountExpires",
           "PrimaryGroupId": "PrimaryGroupId",
           "AllowedToDelegateTo": "AllowedToDelegateTo",
           "OldUacValue": "OldUacValue",  # to convert
           "NewUacValue": "NewUacValue",  # to convert
           "UserParameters": "UserParameters",
           "SidHistory": "SIDHistory",
           "LogonHours": "LogonHours",
           "UserAccountControl": "UserAccountControl",  # %% format
           "DnsHostName": "Hostname",
           "ServicePrincipalNames": "SPNs"},

    4768: {"Descr": "A Kerberos authentication ticket (TGT) was requested",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "TargetUserSid": "TargetSID",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain",
           "ServiceSid": "ServiceSID",
           "ServiceName": "ServiceName",
           "TicketOptions": "+TicketOptions",
           "Status": "+ResultCode",
           "TicketEncryptionType": "+TicketEncryptionType",
           "PreAuthType": "+PreAuthType",
           "IpAddress": "IP",
           "IpPort": "Port",
           "CertIssuerName": "CertIssuer",
           "CertSerialNumber": "CertSerialNumber",
           "CertThumbprint": "CertThumbprint"},

    4769: {"Descr": "A Kerberos service ticket was requested",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain",
           "ServiceSid": "ServiceSID",
           "ServiceName": "ServiceName",
           "TicketOptions": "+TicketOptions",
           "Status": "+ResultCode",
           "TicketEncryptionType": "+TicketEncryptionType",
           "PreAuthType": "+PreAuthType",
           "IpAddress": "IP",
           "IpPort": "Port",
           "LogonGuid": "LogonGUID",
           "TransmittedServices": "TransmittedServices"},

    4771: {"Descr": "Kerberos pre-authentication failed",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "TargetUserName": "TargetUsername",
           "TargetSid": "TargetSID",
           "ServiceName": "ServiceName",
           "TicketOptions": "+TicketOptions",
           "Status": "+ResultCode",
           "PreAuthType": "+PreAuthType",
           "IpAddress": "IP",
           "IpPort": "Port"},

    4776: {"Descr": "The computer attempted to validate the credentials for an account",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "TargetUserName": "TargetUsername",
           "Workstation": "WorkstationName",
           "PackageName": "AuthenticationPackage",
           "Status": "+ResultCode"},

    4778: {"Descr": "A session was reconnected to a Window Station",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "AccountName": "TargetUsername",
           "AccountDomain": "TargetDomain",
           "LogonID": "TargetLogonId",
           "SessionName": "SessionName",
           "ClientName": "WorkstationName",
           "ClientAddress": "IP",
           "PackageName": "AuthenticationPackage"},

    4779: {"Descr": "A session was disconnected from a Window Station",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "AccountName": "TargetUsername",
           "AccountDomain": "TargetDomain",
           "LogonID": "TargetLogonId",
           "SessionName": "SessionName",
           "ClientName": "WorkstationName",
           "ClientAddress": "IP"},

    4798: {"Descr": "A user's local group membership was enumerated",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain",
           "TargetSid": "TargetSID",
           "CallerProcessId": "ProcessId",
           "CallerProcessName": "ProcessPath"},

    4799: {"Descr": "A security-enabled local group membership was enumerated",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "TargetUserName": "TargetUsername",
           "TargetDomainName": "TargetDomain",
           "TargetSid": "TargetSID",
           "CallerProcessId": "ProcessId",
           "CallerProcessName": "ProcessPath"},

    4825: {"Descr": "A user was denied the access to Remote Desktop. By default, users are allowed to connect only "
                    "if they are members of the Remote Desktop Users group or Administrators group",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "AccountName": "TargetUsername",
           "AccountDomain": "TargetDomain",
           "LogonID": "TargetLogonId",
           "ClientAddress": "IP"},

    5059: {"Descr": "Key migration operation",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "ProviderName": "ProviderName",
           "AlgorithmName": "AlgorithmName",
           "KeyName": "KeyName",
           "KeyType": "KeyType",
           "Operation": "OperationType",
           "ReturnCode": "ResultCode"},

    5140: {"Descr": "A network share object was accessed",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "ObjectType": "ObjectType",
           "ShareName": "ShareName",
           "ShareLocalPath": "ShareLocalPath",
           "IpAddress": "IP",
           "IpPort": "Port",
           "AccessList": "AccessList"},  # %% format

    5142: {"Descr": "A network share object was added",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "ShareName": "ShareName",
           "ShareLocalPath": "ShareLocalPath"},

    5144: {"Descr": "A network share object was deleted",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "ShareName": "ShareName",
           "ShareLocalPath": "ShareLocalPath"},

    5145: {"Descr": "A network share object was checked to see whether client can be granted desired access",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "ObjectType": "ObjectType",
           "ShareName": "ShareName",
           "ShareLocalPath": "ShareLocalPath",
           "RelativeTargetName": "RelativeTargetName",
           "IpAddress": "IP",
           "IpPort": "Port",
           "AccessList": "AccessList",  # %% format
           "AccessMask": "AccessMask",  # alternate representation of AccessList
           "AccessReason": "AccessReason"},

    5152: {"Descr": "The Windows Filtering Platform has blocked a packet",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "ProcessId": "ProcessId",
           "Application": "ProcessPath",
           "Direction": "Direction",  # %% format
           "SourceAddress": "IP",
           "SourcePort": "Port",
           "DestAddress": "TargetIP",
           "DestPort": "TargetPort",
           "Protocol": "+Protocol"},

    5156: {"Descr": "The Windows Filtering Platform has permitted a connection",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "ProcessId": "ProcessId",
           "Application": "ProcessPath",
           "Direction": "Direction",  # %% format
           "IpAddress": "IP",
           "IpPort": "Port",
           "DestAddress": "TargetIP",
           "DestPort": "TargetPort",
           "Protocol": "+Protocol",
           "RemoteUserID": "TargetSID",
           "RemoteMachineID": "TargetMachineSID"},

    5158: {"Descr": "The Windows Filtering Platform has permitted a bind to a local port",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "ProcessId": "ProcessId",
           "Application": "ProcessPath",
           "Direction": "Direction",  # %% format
           "SourceAddress": "IP",
           "SourcePort": "Port",
           "Protocol": "+Protocol"},

    6416: {"Descr": "A new external device was recognized by the System",
           "Provider": "Microsoft-Windows-Security-Auditing",
           "SubjectUserSid": "SID",
           "SubjectUserName": "Username",
           "SubjectDomainName": "Domain",
           "SubjectLogonId": "LogonId",
           "DeviceId": "DeviceName",  # Win10 v1511+
           "DeviceDescription": "DeviceDescr",  # Win10 v1511+
           "ClassId": "ClassId",  # Win10 v1511+
           "ClassName": "ClassName",  # Win10 v1511+
           "VendorIds": "VendorId",
           "CompatibleIds": "CompatibleId",
           "LocationInformation": "Location"}
}

sys = {  # System
    2: {"Descr": "Possible detection of CVE: <CVEId>. This event is raised by a kernel mode driver",
        "Provider": "Microsoft-Windows-Audit-CVE",
        "CVEID": "CVEID",
        "AdditionalDetails": "AdditionalDetails"},

    104: {"Descr": "The <EventLogName> log file was cleared",
          "Provider": "Microsoft-Windows-Eventlog",
          "SubjectUserName": "Username",
          "SubjectDomainName": "Domain",
          "Channel": "EventLogName",
          "BackupPath": "BackupPath"},

    1014: {"Descr": "Name resolution for the <QueryName> timed out after none of the configured DNS servers responded",
           "Provider": "Microsoft-Windows-DNS-Client",
           "QueryName": "QueryName",
           "Address": "Address"},

    6100: {"Descr": "Details about Networking <HelperClassName> diagnosis:",
           "Provider": "Microsoft-Windows-Diagnostics-Networking",
           "HelperClassName": "HelperClassName",
           "EventDescription": "EventDescr",
           "EventVerbosity": "EventVerbosity"},

    7034: {"Descr": "The <ServiceName> terminated unexpectedly. It has done this <Count> time(s)",
           "Provider": "Service Control Manager",
           "param1": "ServiceName",
           "param2": "Count"},

    7035: {"Descr": "The <ServiceName> was successfully sent a <Control>",
           "Provider": "Service Control Manager",
           "param1": "ServiceName",
           "param2": "Control"},

    7036: {"Descr": "The <ServiceName> entered the <StatusAfter> state",
           "Provider": "Service Control Manager",
           "param1": "ServiceName",
           "param2": "StatusAfter"},

    7040: {"Descr": "The start type of <ServiceName> was changed from <StatusBefore> to <StatusAfter>",
           "Provider": "Service Control Manager",
           "param1": "ServiceName",
           "param2": "StatusBefore",
           "param3": "StatusAfter"},

    7045: {"Descr": "A service was installed on the system",
           "Provider": "Service Control Manager",
           "ServiceName": "ServiceName",
           "ImagePath": "ServicePath",
           "ServiceType": "ServiceType",
           "StartType": "StartType",
           "AccountName": "Username"},

    9009: {"Descr": "The Desktop Window Manager has exited with code <ExitCode>",  # classic event, incorrect channel?
           "Param1": "ExitCode"},

    10000: {"Descr": "A driver package which uses user-mode driver framework version <FrameworkVersion> is being "
                     "installed on device <DeviceId>",
            "Provider": "Microsoft-Windows-DriverFrameworks-UserMode",
            "DeviceId": "DeviceId",
            "FrameworkVersion": "FrameworkVersion"},

    20001: {"Descr": "Driver Management concluded the process to install <DriverName> for <DeviceInstanceId> "
                     "with <Status>",
            "Provider": "Microsoft-Windows-UserPnp",
            "DriverName": "DriverName",
            "DriverVersion": "DriverVersion",
            "DriverProvider": "DriverProvider",
            "DeviceInstanceID": "DeviceInstanceID",
            "DriverDescription": "DriverDescr",
            "SetupClass": "SetupClass",
            "RebootOption": "RebootOption",
            "UpgradeDevice": "UpgradeDevice",
            "IsDriverOEM": "IsDriverOEM",
            "InstallStatus": "Status"},

    20002: {"Descr": "Driver Management concluded the process to remove <DriverName> from <DeviceInstanceId> "
                     "with <Status>",
            "Provider": "Microsoft-Windows-UserPnp",
            "DriverName": "DriverName",
            "DriverVersion": "DriverVersion",
            "DriverProvider": "DriverProvider",
            "DeviceInstanceID": "DeviceInstanceID",
            "DriverDescription": "DriverDescr",
            "SetupClass": "SetupClass",
            "RebootOption": "RebootOption",
            "UpgradeDevice": "UpgradeDevice",
            "IsDriverOEM": "IsDriverOEM",
            "InstallStatus": "Status"},

    20003: {"Descr": "Driver Management has concluded the process to add <ServiceName>> for <DeviceInstanceID> "
                     "with <Status>",
            "Provider": "Microsoft-Windows-UserPnp",
            "ServiceName": "DriverName",
            "DriverFileName": "DriverPath",
            "DeviceInstanceID": "DeviceInstanceID",
            "PrimaryService": "IsPrimaryService",
            "UpdateService": "IsUpdateService",
            "AddServiceStatus": "AddServiceStatus"}
}

app = {  # Application
    1: {"Descr": "Possible detection of CVE: <CVEId>. This event is raised by a User mode process",
        "Provider": "Microsoft-Windows-Audit-CVE",
        "CVEID": "CVEID",
        "AdditionalDetails": "AdditionalDetails"},

    216: {"Descr": "%1 (%2) %3 A database location change was detected from %4 to %5",
          "Provider": "ESENT"},

    325: {"Descr": "%1 (%2) %3 The database engine created a new database (%4, %5). (Time=%6 seconds)",
          "Provider": "ESENT"},

    326: {"Descr": "%1 (%2) %3 The database engine attached a database (%4, %5). (Time=%6 seconds)",
          "Provider": "ESENT"},

    327: {"Descr": "%1 (%2) %3 The database engine detached a database (%4, %5). (Time=%6 seconds)",
          "Provider": "ESENT"},

    1001: {"Descr": "Process Error",
           "Provider": "Windows Error Reporting"}
}

appexp1 = {  # Microsoft-Windows-Application-Experience/Program-Inventory
    800: {"Descr": "An instance of Program Data Updater (PDU) ran with the following information...",  # Win7 - 8.1
          "Provider": "Microsoft-Windows-Application-Experience",
          "StartTime": "StartTime",
          "StopTime": "StopTime",
          "ExitCode": "ExitCode",
          "NumNewPrograms": "NumNewPrograms",
          "NumRemovedPrograms": "NumRemovedPrograms",
          "NumUpdatedPrograms": "NumUpdatedPrograms",
          "NumInstalledPrograms": "NumInstalledPrograms",
          "NumNewOrphans": "NumNewOrphans",
          "NumNewAddOns": "NumNewAddOns",
          "NumRemovedAddOns": "NumRemovedAddOns",
          "NumUpdatedAddOns": "NumUpdatedAddOns",
          "NumInstalledAddOns": "NumInstalledAddOns",
          "NumNewInstallations": "NumNewInstallations"}
}

appexp2 = {  # Microsoft-Windows-Application-Experience/Program-Telemetry
    500: {"Descr": "Compatibility fix applied to <ProcessPath>.  Fix information: <FixName>, <FixId>, <Flags>",
          "Provider": "Microsoft-Windows-Application-Experience",
          "ProcessId": "ProcessId",
          "ExePath": "ProcessPath",
          "StartTime": "StartTime",
          "FixID": "FixId",
          "FixName": "FixName",
          "Flags": "Flags"},

    501: {"Descr": "Compatibility fix applied to <ProcessPath>.  Fix information: <FixName>, <FixId>, <Flags>",
          "Provider": "Microsoft-Windows-Application-Experience",
          "ProcessId": "ProcessId",
          "ExePath": "ProcessPath",
          "StartTime": "StartTime",
          "FixID": "FixId",
          "FixName": "FixName",
          "Flags": "Flags"},

    502: {"Descr": "Compatibility fix applied to <MsiPath>.  Fix information: <FixName>, <FixId>, <Flags>",
          "Provider": "Microsoft-Windows-Application-Experience",
          "ClientProcessId": "ProcessId",
          "ClientStartTime": "StartTime",
          "FixID": "FixId",
          "FixName": "FixName",
          "Flags": "Flags",
          "ProductCode": "ProductCode",
          "PackageCode": "PackageCode",
          "MsiPath": "MsiPath"},

    503: {"Descr": "Compatibility fix applied to <MsiPath>.  Fix information: <FixName>, <FixId>, <Flags>",
          "Provider": "Microsoft-Windows-Application-Experience",
          "ClientProcessId": "ProcessId",
          "ClientStartTime": "StartTime",
          "FixID": "FixId",
          "FixName": "FixName",
          "Flags": "Flags",
          "ProductCode": "ProductCode",
          "PackageCode": "PackageCode",
          "MsiPath": "MsiPath"}
}

applocker = {  # Microsoft-Windows-AppLocker/EXE and DLL
    8004: {"Descr": "<FilePath> was prevented from running",
           "Provider": "Microsoft-Windows-AppLocker",
           "PolicyNameBuffer": "Policy",
           "RuleId": "RuleId",
           "RuleNameBuffer": "RuleName",
           "RuleSddlBuffer": "RuleSddl",
           "TargetUser": "TargetUsername",
           "TargetLogonId": "TargetLogonId",
           "TargetProcessId": "TargetProcessId",
           "FilePathBuffer": "FilePath",
           "FileHash": "FileHash",
           "Fqbn": "Fqbn"}
}

bits = {  # Microsoft-Windows-Bits-Client/Operational
    4: {"Descr": "The transfer job is complete",
        "Provider": "Microsoft-Windows-Bits-Client",
        "User": "Username",
        "jobTitle": "JobTitle",
        "jobId": "JobId",
        "jobOwner": "JobOwner",
        "fileCount": "FileCount"},

    59: {"Descr": "BITS started the <Name> transfer job that is associated with the <URL>",
         "Provider": "Microsoft-Windows-Bits-Client",
         "transferId": "TransferId",
         "name": "Name",
         "Id": "JobId",
         "url": "URL",
         "peer": "Peer",
         "fileTime": "FileTime",
         "fileLength": "FileSize"},

    60: {"Descr": "BITS stopped transferring the <Name> transfer job that is associated with the <URL>",
         "Provider": "Microsoft-Windows-Bits-Client",
         "transferId": "TransferId",
         "name": "Name",
         "Id": "JobId",
         "url": "URL",
         "peer": "Peer",
         "fileTime": "FileTime",
         "fileLength": "FileSize",
         "bytesTotal": "BytesTotal",
         "bytesTransferred": "BytesTransferred",
         "bytesTransferredFromPeer": "BytesTransferredFromPeer"}
}

codeinteg = {  # Microsoft-Windows-CodeIntegrity/Operational
    3001: {"Descr": "Code Integrity determined an unsigned kernel module <FileName> is loaded into the system",
           "Provider": "Microsoft-Windows-CodeIntegrity",
           "FileNameBuffer": "FileName"}
}

diag = {  # Microsoft-Windows-Diagnostics-Performance/Operational
    100: {"Descr": "Windows has started up",
          "Provider": "Microsoft-Windows-Diagnostics-Performance",
          "BootStartTime": "BootStartTime",
          "BootEndTime": "BootEndTime",
          "SystemBootInstance": "SystemBootInstance",
          "UserBootInstance": "UserBootInstance",
          "BootTime": "BootTime",  # in milliseconds
          "UserLogonWaitDuration": "UserLogonWaitDuration"},

    200: {"Descr": "Windows has shutdown",
          "Provider": "Microsoft-Windows-Diagnostics-Performance",
          "ShutdownStartTime": "ShutdownStartTime",
          "ShutdownEndTime": "ShutdownEndTime",
          "ShutdownTime": "ShutdownTime"}  # in milliseconds
}

dnsclient = {  # Microsoft-Windows-DNS-Client/Operational (disabled by default)
    1014: {"Descr": "Name resolution for the <QueryName> timed out after none of the configured "
                    "DNS servers responded",
           "Provider": "Microsoft-Windows-DNS-Client",
           "QueryName": "QueryName",
           "Address": "Address"},

    3006: {"Descr": "DNS query is called for the <QueryName>, <QueryType>",
           "Provider": "Microsoft-Windows-DNS-Client",
           "QueryName": "QueryName",
           "QueryType": "+QueryType",
           "QueryOptions": "QueryOptions",
           "ServerList": "ServerList",
           "IsNetworkQuery": "IsNetworkQuery",
           "NetworkQueryIndex": "NetworkIndex",
           "InterfaceIndex": "InterfaceIndex",
           "IsAsyncQuery": "IsAsyncQuery"},

    3008: {"Descr": "DNS query is completed for the <QueryName>, <QueryType> with <ResponseCode> <QueryResults>",
           "Provider": "Microsoft-Windows-DNS-Client",
           "QueryName": "QueryName",
           "QueryType": "+QueryType",
           "QueryOptions": "QueryOptions",
           "QueryStatus": "ResponseCode",
           "QueryResults": "QueryResults"},

    3011: {"Descr": "Received response from <DnsServerIP> for <QueryName> and <QueryType> with <ResponseCode>",
           "Provider": "Microsoft-Windows-DNS-Client",
           "QueryName": "QueryName",
           "QueryType": "+QueryType",
           "DnsServerIpAddress": "DnsServerIP",
           "ResponseStatus": "Status"},

    3016: {"Descr": "Cache lookup called for <QueryName>, <QueryType>",
           "Provider": "Microsoft-Windows-DNS-Client",
           "QueryName": "QueryName",
           "QueryType": "+QueryType",
           "QueryOptions": "QueryOptions",
           "InterfaceIndex": "InterfaceIndex"},

    3018: {"Descr": "Cache lookup for <QueryName>, <QueryType> returned <ResponseCode> with <QueryResults>",
           "Provider": "Microsoft-Windows-DNS-Client",
           "QueryName": "QueryName",
           "QueryType": "+QueryType",
           "QueryOptions": "QueryOptions",
           "Status": "ResponseCode",
           "QueryResults": "QueryResults"},

    3019: {"Descr": "Query wire called for name <QueryName>, <QueryType>",
           "Provider": "Microsoft-Windows-DNS-Client",
           "QueryName": "QueryName",
           "QueryType": "+QueryType",
           "NetworkIndex": "NetworkIndex",
           "InterfaceIndex": "InterfaceIndex"},

    3020: {"Descr": "Query response for name <QueryName>, <QueryType> returned <ResponseCode> with <QueryResults>",
           "Provider": "Microsoft-Windows-DNS-Client",
           "QueryName": "QueryName",
           "QueryType": "+QueryType",
           "NetworkIndex": "NetworkIndex",
           "InterfaceIndex": "InterfaceIndex",
           "Status": "ResponseCode",
           "QueryResults": "QueryResults"}
}

dnsserver = {  # Microsoft-Windows-DNSServer/Analytical (Windows Server 2016+)
    256: {"Descr": "Query received",
          "Provider": "Microsoft-Windows-DNSServer",
          "TCP": "TCP",
          "InterfaceIP": "InterfaceIP",
          "Source": "Source",
          "RD": "RD",
          "QNAME": "QueryName",
          "QTYPE": "QueryType",
          "XID": "XID",
          "Port": "Port",
          "Flags": "Flags",
          "PacketData": "PacketData",
          "AdditionalInfo": "AdditionalInfo"},

    257: {"Descr": "Response success",
          "Provider": "Microsoft-Windows-DNSServer",
          "TCP": "TCP",
          "InterfaceIP": "InterfaceIP",
          "Destination": "Destination",
          "AA": "AA",
          "AD": "AD",
          "QNAME": "QueryName",
          "QTYPE": "QueryType",
          "XID": "XID",
          "DNSSEC": "DNSSEC",
          "RCODE": "RCode",
          "Port": "Port",
          "Flags": "Flags",
          "Scope": "Scope",
          "Zone": "Zone",
          "PolicyName": "Policy",
          "PacketData": "PacketData",
          "AdditionalInfo": "AdditionalInfo"},

    258: {"Descr": "Response failure",
          "Provider": "Microsoft-Windows-DNSServer",
          "TCP": "TCP",
          "InterfaceIP": "InterfaceIP",
          "Reason": "Reason",
          "Destination": "Destination",
          "QNAME": "QueryName",
          "QTYPE": "QueryType",
          "XID": "XID",
          "RCODE": "RCode",
          "Port": "Port",
          "Flags": "Flags",
          "Zone": "Zone",
          "PolicyName": "Policy",
          "PacketData": "PacketData",
          "AdditionalInfo": "AdditionalInfo"},

    259: {"Descr": "Ignored query",
          "Provider": "Microsoft-Windows-DNSServer",
          "TCP": "TCP",
          "InterfaceIP": "InterfaceIP",
          "Source": "Source",
          "Reason": "Reason",
          "QNAME": "QueryName",
          "QTYPE": "QueryType",
          "XID": "XID",
          "Zone": "Zone",
          "PolicyName": "Policy",
          "AdditionalInfo": "AdditionalInfo"},

    260: {"Descr": "Recurse query out",
          "Provider": "Microsoft-Windows-DNSServer",
          "TCP": "TCP",
          "InterfaceIP": "InterfaceIP",
          "Destination": "Destination",
          "RD": "RD",
          "QNAME": "QueryName",
          "QTYPE": "QueryType",
          "XID": "XID",
          "Port": "Port",
          "Flags": "Flags",
          "RecursionScope": "RecursionScope",
          "CacheScope": "CacheScope",
          "PolicyName": "Policy",
          "PacketData": "PacketData",
          "AdditionalInfo": "AdditionalInfo"},

    261: {"Descr": "Recurse response in",
          "Provider": "Microsoft-Windows-DNSServer",
          "TCP": "TCP",
          "InterfaceIP": "InterfaceIP",
          "Source": "Source",
          "AA": "AA",
          "AD": "AD",
          "QNAME": "QueryName",
          "QTYPE": "QueryType",
          "XID": "XID",
          "Port": "Port",
          "Flags": "Flags",
          "RecursionScope": "RecursionScope",
          "CacheScope": "CacheScope",
          "PacketData": "PacketData",
          "AdditionalInfo": "AdditionalInfo"},

    262: {"Descr": "Recurse query timeout",
          "Provider": "Microsoft-Windows-DNSServer",
          "TCP": "TCP",
          "InterfaceIP": "InterfaceIP",
          "Destination": "Destination",
          "QNAME": "QueryName",
          "QTYPE": "QueryType",
          "XID": "XID",
          "Port": "Port",
          "Flags": "Flags",
          "RecursionScope": "RecursionScope",
          "CacheScope": "CacheScope",
          "AdditionalInfo": "AdditionalInfo"}
}

driverfw = {  # Microsoft-Windows-DriverFrameworks-UserMode/Operational
    2003: {"Descr": "The UMDF Host Process (<HostProcessId>) has been asked to load drivers for device <DeviceId>",
           "Provider": "Microsoft-Windows-DriverFrameworks-UserMode",
           "LifetimeId": "HostProcessId",
           "InstanceId": "DeviceId"},

    2004: {"Descr": "The UMDF Host is loading <Driver> at <Level> for device <DeviceId>",
           "Provider": "Microsoft-Windows-DriverFrameworks-UserMode",
           "LifetimeId": "HostProcessId",
           "InstanceId": "DeviceId",
           "Level": "Level",
           "Service": "Driver",
           "ClsId": "DriverClassId"},

    2005: {"Descr": "The UMDF Host Process (<HostProcessId>) has loaded <ModulePath> while loading drivers for device "
                    "<DeviceId>",
           "Provider": "Microsoft-Windows-DriverFrameworks-UserMode",
           "LifetimeId": "HostProcessId",
           "InstanceId": "DeviceId",
           "ModulePath": "ModulePath",
           "CompanyName": "CompanyName",
           "FileDescription": "FileDescr",
           "FileVersion": "FileVersion"},

    2010: {"Descr": "The UMDF Host Process (<HostProcessId>) has successfully loaded drivers for device <DeviceId>",
           "Provider": "Microsoft-Windows-DriverFrameworks-UserMode",
           "LifetimeId": "HostProcessId",
           "InstanceId": "DeviceId",
           "FinalStatus": "FinalStatus"},

    2100: {"Descr": "Received a Pnp or Power operation (<MajorCode>, <MinorCode>) for device <DeviceId>",
           "Provider": "Microsoft-Windows-DriverFrameworks-UserMode",
           "LifetimeId": "HostProcessId",
           "InstanceId": "DeviceId",
           "MajorCode": "MajorCode",
           "MinorCode": "MinorCode",
           "Status": "Status"},

    2102: {"Descr": "Forwarded a finished Pnp or Power operation (<MajorCode>, <MinorCode>) to the lower driver "
                    "for device <DeviceId> with <Status>",
           "Provider": "Microsoft-Windows-DriverFrameworks-UserMode",
           "LifetimeId": "HostProcessId",
           "InstanceId": "DeviceId",
           "MajorCode": "MajorCode",
           "MinorCode": "MinorCode",
           "Status": "Status"},

    2105: {"Descr": "Forwarded a Pnp or Power operation (<MajorCode>, <MinorCode>) for device <DeviceId> to the "
                    "lower driver with <Status>",
           "Provider": "Microsoft-Windows-DriverFrameworks-UserMode",
           "LifetimeId": "HostProcessId",
           "InstanceId": "DeviceId",
           "MajorCode": "MajorCode",
           "MinorCode": "MinorCode",
           "Status": "Status"}
}

fwall = {  # Microsoft-Windows-Windows Firewall With Advanced Security/Firewall
    2004: {"Descr": "A rule has been added to the Windows Firewall exception list",
           "Provider": "Microsoft-Windows-Windows Firewall With Advanced Security",
           "RuleId": "RuleId",
           "RuleName": "RuleName",
           "Origin": "+Origin",
           "ApplicationPath": "ApplicationPath",
           "ServiceName": "ServiceName",
           "Direction": "+Direction",
           "Protocol": "+Protocol",
           "LocalPorts": "TargetPort",
           "RemotePorts": "RemotePorts",
           "Action": "+Action",
           "Profiles": "+Profiles",
           "LocalAddresses": "TargetIP",
           "EmbeddedContext": "EmbeddedContext",
           "Active": "+Active",
           "ModifyingUser": "SID",
           "ModifyingApplication": "ProcessPath"},

    2005: {"Descr": "A rule has been modified in the Windows Firewall exception list",
           "Provider": "Microsoft-Windows-Windows Firewall With Advanced Security",
           "RuleId": "RuleId",
           "RuleName": "RuleName",
           "Origin": "+Origin",
           "ApplicationPath": "ApplicationPath",
           "ServiceName": "ServiceName",
           "Direction": "+Direction",
           "Protocol": "+Protocol",
           "LocalPorts": "TargetPort",
           "RemotePorts": "RemotePorts",
           "Action": "+Action",
           "Profiles": "+Profiles",
           "LocalAddresses": "TargetIP",
           "EmbeddedContext": "EmbeddedContext",
           "Active": "+Active",
           "ModifyingUser": "SID",
           "ModifyingApplication": "ProcessPath"},

    2006: {"Descr": "A rule has been deleted in the Windows Firewall exception list",
           "Provider": "Microsoft-Windows-Windows Firewall With Advanced Security",
           "RuleId": "RuleId",
           "RuleName": "RuleName",
           "ModifyingUser": "SID",
           "ModifyingApplication": "ProcessPath"}
}

kernelpnp = {  # Microsoft-Windows-Kernel-PnP/Configuration
    400: {"Descr": "<DeviceInstanceId> was configured",
          "Provider": "Microsoft-Windows-Kernel-PnP",
          "DeviceInstanceId": "DeviceInstanceId",
          "DriverName": "DriverName",
          "ClassGuid": "+ClassGuid",
          "DriverDate": "DriverDate",
          "DriverVersion": "DriverVersion",
          "DriverProvider": "DriverProvider",
          "DriverInbox": "IsDriverInbox",
          "DriverSection": "DriverSection",
          "DeviceId": "DeviceId",
          "OutrankedDrivers": "OutrankedDrivers",
          "DeviceUpdated": "IsDeviceUpdated",
          "Status": "Status",
          "ParentDeviceInstanceId": "ParentDeviceInstanceId"},

    410: {"Descr": "<DeviceInstanceId> was started",
          "Provider": "Microsoft-Windows-Kernel-PnP",
          "DeviceInstanceId": "DeviceInstanceId",
          "DriverName": "DriverName",
          "ClassGuid": "+ClassGuid",
          "ServiceName": "ServiceName",
          "LowerFilters": "LowerFilters",
          "UpperFilters": "UpperFilters",
          "Problem": "Problem",
          "Status": "Status"},

    430: {"Descr": "<DeviceInstanceId> requires further installation",
          "Provider": "Microsoft-Windows-Kernel-PnP",
          "DeviceInstanceId": "DeviceInstanceId"}
}

lsm = {  # Microsoft-Windows-TerminalServices-LocalSessionManager/Operational
    21: {"Descr": "Remote Desktop Services: Session logon succeeded",
         "Provider": "Microsoft-Windows-TerminalServices-LocalSessionManager",
         "User": "TargetUsername",
         "SessionID": "TargetSessionId",
         "Address": "IP"},

    22: {"Descr": "Remote Desktop Services: Shell start notification received",
         "Provider": "Microsoft-Windows-TerminalServices-LocalSessionManager",
         "User": "TargetUsername",
         "SessionID": "TargetSessionId",
         "Address": "IP"},

    23: {"Descr": "Remote Desktop Services: Session logoff succeeded",
         "Provider": "Microsoft-Windows-TerminalServices-LocalSessionManager",
         "User": "TargetUsername",
         "SessionID": "TargetSessionId"},

    24: {"Descr": "Remote Desktop Services: Session has been disconnected",
         "Provider": "Microsoft-Windows-TerminalServices-LocalSessionManager",
         "User": "TargetUsername",
         "SessionID": "TargetSessionId",
         "Address": "IP"},

    25: {"Descr": "Remote Desktop Services: Session reconnection succeeded",
         "Provider": "Microsoft-Windows-TerminalServices-LocalSessionManager",
         "User": "TargetUsername",
         "SessionID": "TargetSessionId",
         "Address": "IP"},

    39: {"Descr": "<TargetSessionId> has been disconnected by session <SessionId>",
         "Provider": "Microsoft-Windows-TerminalServices-LocalSessionManager",
         "TargetSession": "TargetSessionId",
         "Source": "SessionId"},

    40: {"Descr": "<TargetSessionId> has been disconnected, <Reason>",
         "Provider": "Microsoft-Windows-TerminalServices-LocalSessionManager",
         "Session": "TargetSessionId",
         "Reason": "+Reason"},

    41: {"Descr": "Begin session arbitration",  # Win8.1+
         "Provider": "Microsoft-Windows-TerminalServices-LocalSessionManager",
         "User": "TargetUsername",
         "SessionID": "TargetSessionId"}
}

ntfs = {  # Microsoft-Windows-Ntfs/Operational
    142: {"Descr": "Summary of disk space usage, since last event",
          "Provider": "Microsoft-Windows-Ntfs",
          "VolumeGuid": "VolumeGuid",
          "VolumeName": "VolumeName",
          "LowestFreeSpaceInBytes": "LowestFreeSpaceInBytes",
          "HighestFreeSpaceInBytes": "HighestFreeSpaceInBytes",
          "IsBootVolume": "IsBootVolume"},

    145: {"Descr": "IO latency summary common data for volume",
          "Provider": "Microsoft-Windows-Ntfs",
          "VolumeCorrelationId": "VolumeGuid",
          "VolumeName": "VolumeName",
          "IsBootVolume": "IsBootVolume"}
}

offlinef = {  # Microsoft-Windows-OfflineFiles/Operational
    7: {"Descr": "User logon detected: <Username> <Session>",
        "Provider": "Microsoft-Windows-OfflineFiles",
        "Account": "TargetUsername",
        "Session": "TargetSessionId"},

    8: {"Descr": "User logoff detected: <Username> <Session>",
        "Provider": "Microsoft-Windows-OfflineFiles",
        "Account": "TargetUsername",
        "Session": "TargetSessionId"}
}

partition = {  # Microsoft-Windows-Partition/Diagnostic; Win10 v1709+
    1006: {"Descr": "A device is connected or disconnected from the system",
           "Provider": "Microsoft-Windows-Partition",
           "Version": "Version",
           "DiskNumber": "DiskNumber",
           "Flags": "Flags",
           "Characteristics": "Characteristics",
           "BytesPerSector": "BytesPerSector",
           "BytesPerLogicalSector": "BytesPerLogicalSector",
           "BytesPerPhysicalSector": "BytesPerPhysicalSector",
           "BytesOffsetForSectorAlignment": "BytesOffsetForSectorAlignment",
           "Capacity": "Capacity",
           "BusType": "+BusType",
           "Manufacturer": "Vendor",
           "Model": "Product",
           "Revision": "ProductRevision",
           "SerialNumber": "SerialNumber",
           "Location": "Location",
           "ParentId": "ParentId",
           "DiskId": "DiskId",
           "AdapterId": "AdapterId",
           "RegistryId": "RegistryId",
           "PoolId": "PoolId",
           "StorageIdType": "+StorageIdType",
           "StorageIdAssociation": "+StorageIdAssoc",
           "StorageId": "StorageId",
           "IsTrimSupported": "IsTrimSupported",
           "IsThinProvisioned": "IsThinProvisioned",
           "HybridSupported": "HybridSupported",
           "HybridCacheBytes": "HybridCacheBytes",
           "AdapterSerialNumber": "AdapterSerialNumber",
           "UserRemovalPolicy": "UserRemovalPolicy",
           "PartitionStyle": "+PartitionStyle",
           "PartitionCount": "PartitionCount",
           "PartitionTableBytes": "PartitionTableBytes",
           "MbrBytes": "MbrBytes",
           "Vbr0Bytes": "Vbr0Bytes",
           "Vbr1Bytes": "Vbr1Bytes",
           "Vbr2Bytes": "Vbr2Bytes",
           "Vbr3Size": "Vbr3Bytes"}
}

printsvc = {  # Microsoft-Windows-PrintService/Operational
    307: {"Descr": "Spooler operation succeeded",
          "Provider": "Microsoft-Windows-PrintService",
          "param1": "JobId",
          "param2": "JobName",
          "param3": "DocumentOwner",
          "param4": "Host",
          "param5": "PrinterName",
          "param6": "PrinterPort",
          "param7": "Size",
          "param8": "Pages"}
}

pshell1 = {  # Windows PowerShell
    400: {"Descr": "Engine state is changed from <PreviousEngineState> to <NewEngineState>"},  # start of session

    403: {"Descr": "Engine state is changed from <PreviousEngineState> to <NewEngineState>"},  # end of session

    500: {"Descr": "Command <CommandName> is <NewCommandState>"},  # start of execution

    501: {"Descr": "Command <CommandName> is <NewCommandState>"},  # end of execution

    600: {"Descr": "Provider <ProviderName> is <NewProviderState>"},

    800: {"Descr": "Pipeline execution details for command line: <CommandLine>"}
}

pshell2 = {  # Microsoft-Windows-PowerShell/Operational
    4103: {"Descr": "<Payload> Context: <ContextInfo>",  # Module logging
           "Provider": "Microsoft-Windows-PowerShell",
           "UserData": "UserData",
           "Payload": "Payload"},

    4104: {"Descr": "Creating Scriptblock text (<MessageNumber> of <MessageTotal>)",  # Scriptblock module logging
           "Provider": "Microsoft-Windows-PowerShell",
           "MessageNumber": "MessageNumber",
           "MessageTotal": "MessageTotal",
           "ScriptBlockText": "ScriptBlockText",
           "ScriptBlockId": "ScriptBlockId",
           "Path": "Path"},

    8193: {"Descr": "Creating Runspace object",  # Session created
           "Provider": "Microsoft-Windows-PowerShell",
           "param1": "InstanceId"},

    8194: {"Descr": "Creating RunspacePool object",  # Session created
           "Provider": "Microsoft-Windows-PowerShell",
           "InstanceId": "InstanceId",
           "MaxRunspaces": "MaxRunspaces",
           "MinRunspaces": "MinRunspaces"},

    8197: {"Descr": "Runspace state changed to <Status>",  # Session status
           "Provider": "Microsoft-Windows-PowerShell",
           "param1": "Status"},

    40961: {"Descr": "PowerShell console is starting up",
            "Provider": "Microsoft-Windows-PowerShell"},  # empty

    40962: {"Descr": "PowerShell console is ready for user input",
            "Provider": "Microsoft-Windows-PowerShell"},  # empty

    53504: {"Descr": "Windows PowerShell has started an IPC listening thread on <ProcessPath> in <AppDomain>",
            "Provider": "Microsoft-Windows-PowerShell",
            "param1": "ProcessId",
            "param2": "AppDomain"}
}

rcm = {  # Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational
    1149: {"Descr": "Remote Desktop Services: User authentication established",
           "Provider": "Microsoft-Windows-TerminalServices-RemoteConnectionManager",
           "Param1": "TargetUsername",
           "Param2": "TargetDomain",
           "Param3": "IP"}
}

rdpclient = {  # Microsoft-Windows-TerminalServices-RDPClient/Operational
    1024: {"Descr": "RDP ClientActiveX is trying to connect to <TargetHost>",
           "Provider": "Microsoft-Windows-TerminalServices-ClientActiveXCore",
           "Value": "TargetHost"},

    1026: {"Descr": "RDP ClientActiveX has been disconnected: <Reason>",
           "Provider": "Microsoft-Windows-TerminalServices-ClientActiveXCore",
           "Value": "Reason"},

    1027: {"Descr": "Connected to <TargetDomain> with <TargetSessionId>",
           "Provider": "Microsoft-Windows-TerminalServices-ClientActiveXCore",
           "DomainName": "TargetDomain",
           "SessionID": "TargetSessionId"},

    1029: {"Descr": "This event is raised during the connection process: Base64(SHA256(<TargetUsername))",
           "Provider": "Microsoft-Windows-TerminalServices-ClientActiveXCore",
           "TraceMessage": "TargetUsername"},

    1102: {"Descr": "This event is raised during the connection process",
           "Provider": "Microsoft-Windows-TerminalServices-ClientActiveXCore",
           "Value": "TargetIP"}
}

rdpcorets = {  # Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
    98: {"Descr": "A TCP connection has been successfully established",
         "Provider": "Microsoft-Windows-RemoteDesktopServices-RdpCoreTS"},

    131: {"Descr": "The server accepted a new <Protocol> connection from <IPPort>",
          "Provider": "Microsoft-Windows-RemoteDesktopServices-RdpCoreTS",
          "ConnType": "Protocol",
          "ClientIP": "IPPort"},

    148: {"Descr": "<ChannelName> has been closed between the server and the client on transport tunnel <TunnelID>",
          "Provider": "Microsoft-Windows-RemoteDesktopServices-RdpCoreTS",
          "ChannelName": "ChannelName",
          "TunnelID": "TunnelID"}
}

scpnp = {  # Microsoft-Windows-Storage-ClassPnP/Operational
    507: {"Descr": "Completing a failed non-ReadWrite SCSI SRB request",
          "Provider": "Microsoft-Windows-StorDiag",
          "DeviceGUID": "DeviceGuid",
          "DeviceNumber": "DeviceNumber",
          "Vendor": "Vendor",
          "Model": "Product",
          "FirmwareVersion": "ProductRevision",
          "SerialNumber": "SerialNumber"}
}

sch = {  # Microsoft-Windows-TaskScheduler/Operational
    106: {"Descr": "<Username> registered Task Scheduler <TaskName>",
          "Provider": "Microsoft-Windows-TaskScheduler",
          "TaskName": "TaskName",
          "UserContext": "Username"},

    118: {"Descr": "Task Scheduler launched <TaskInstanceId> of <TaskName> due to system startup",
          "Provider": "Microsoft-Windows-TaskScheduler",
          "TaskName": "TaskName",
          "InstanceId": "TaskInstanceId"},

    119: {"Descr": "Task Scheduler launched <TaskInstanceId of <TaskName> due to <Username> logon",
          "Provider": "Microsoft-Windows-TaskScheduler",
          "TaskName": "TaskName",
          "UserName": "Username",
          "InstanceId": "TaskInstanceId"},

    140: {"Descr": "<Username> updated Task Scheduler <TaskName>",
          "Provider": "Microsoft-Windows-TaskScheduler",
          "TaskName": "TaskName",
          "UserName": "Username"},

    141: {"Descr": "<Username> deleted Task Scheduler <TaskName>",
          "Provider": "Microsoft-Windows-TaskScheduler",
          "TaskName": "TaskName",
          "UserName": "Username"},

    200: {"Descr": "Task Scheduler launched <ApplicationPath> in <TaskInstanceId> of <TaskName>",
          "Provider": "Microsoft-Windows-TaskScheduler",
          "TaskName": "TaskName",
          "ActionName": "ApplicationPath",
          "TaskInstanceId": "TaskInstanceId"},

    201: {"Descr": "Task Scheduler successfully completed <TaskName>, <TaskInstanceId>, <ApplicationPath>",
          "Provider": "Microsoft-Windows-TaskScheduler",
          "TaskName": "TaskName",
          "ActionName": "ApplicationPath",
          "TaskInstanceId": "TaskInstanceId",
          "ResultCode": "ResultCode"},
}

shell = {  # Microsoft-Windows-Shell-Core/Operational
    9707: {"Descr": "Started execution of <Command>",  # from Run/RunOnce
           "Provider": "Microsoft-Windows-Shell-Core",
           "Command": "Command"},

    9708: {"Descr": "Finished execution of <Command> (PID <ProcessPid>)",  # from Run/RunOnce
           "Provider": "Microsoft-Windows-Shell-Core",
           "Command": "Command",
           "PID": "ProcessId"}
}

smbclient = {  # Microsoft-Windows-SmbClient/Security
    31001: {"Descr": "Failed logon to <ServerName>",
            "Provider": "Microsoft-Windows-SmbClient",
            "Reason": "Reason",
            "Status": "Status",
            "SecurityStatus": "SecurityStatus",
            "TargetLogonId": "TargetLogonId",
            "UserName": "TargetUsername",
            "ServerName": "TargetHost",
            "PrincipalName": "PrincipalName"},  # TODO - change to SPN?

    31010: {"Descr": "The SMB client failed to connect to the share.",
            "Provider": "Microsoft-Windows-SmbClient",
            "Reason": "Reason",
            "Status": "Status",
            "ShareName": "ShareName",
            "ObjectName": "ObjectName"}
}

smbserver1 = {  # Microsoft-Windows-SMBServer/Analytic
    551: {"Descr": "Smb Session Authentication Failure",
          "Provider": "Microsoft-Windows-SMBServer",
          "SessionGUID": "SessionGuid",
          "ConnectionGUID": "ConnectionGuid",
          "Status": "Status"},

    552: {"Descr": "SMB2 Session Authentication Success",
          "Provider": "Microsoft-Windows-SMBServer",
          "SessionGUID": "SessionGuid",
          "ConnectionGUID": "ConnectionGuid",
          "UserName": "TargetUsername",
          "DomainName": "TargetDomain"},

    553: {"Descr": "SMB2 Session Bound to Connection",
          "Provider": "Microsoft-Windows-SMBServer",
          "SessionGUID": "SessionGuid",
          "ConnectionGUID": "ConnectionGuid",
          "BindingSessionGUID": "BindingSessionGuid"},

    554: {"Descr": "Session Terminated",
          "Provider": "Microsoft-Windows-SMBServer",
          "SessionGUID": "SessionGuid",
          "Reason": "Reason"},

    600: {"Descr": "SMB2 TreeConnect Allocated",
          "Provider": "Microsoft-Windows-SMBServer",
          "TreeConnectGUID": "TreeConnectGuid",
          "SessionGUID": "SessionGuid",
          "ConnectionGUID": "ConnectionGuid",
          "ShareGUID": "ShareGuid",
          "ShareName": "ShareName",
          "ScopeName": "ScopeName",
          "ShareProperties": "ShareProperties"},

    601: {"Descr": "SMB2 TreeConnect Disconnected",
          "Provider": "Microsoft-Windows-SMBServer",
          "TreeConnectGUID": "TreeConnectGuid",
          "SessionGUID": "SessionGuid",
          "ConnectionGUID": "ConnectionGuid"},

    602: {"Descr": "SMB2 TreeConnect Terminated",
          "Provider": "Microsoft-Windows-SMBServer",
          "TreeConnectGUID": "TreeConnectGuid",
          "SessionGUID": "SessionGuid"},

    700: {"Descr": "SMB2 Share Added",
          "Provider": "Microsoft-Windows-SMBServer",
          "ShareName": "ShareName",
          "ServerName": "ServerName",
          "PathName": "PathName",
          "CSCState": "CSCState",
          "ClusterShareType": "ClusterShareType",
          "ShareProperties": "ShareProperties",
          "CaTimeOut": "CaTimeOut",
          "ShareState": "ShareState"},

    701: {"Descr": "SMB2 Share Modified",
          "Provider": "Microsoft-Windows-SMBServer",
          "ShareName": "ShareName",
          "ServerName": "ServerName",
          "PathName": "PathName",
          "CSCState": "CSCState",
          "ClusterShareType": "ClusterShareType",
          "ShareProperties": "ShareProperties",
          "CaTimeOut": "CaTimeOut",
          "ShareState": "ShareState"},

    702: {"Descr": "SMB2 Share Deleted",
          "Provider": "Microsoft-Windows-SMBServer",
          "ShareName": "ShareName",
          "ServerName": "ServerName"}
}

smbserver2 = {  # Microsoft-Windows-SMBServer/Auditr
    3000: {"Descr": "SMB1 access",
           "Provider": "Microsoft-Windows-SMBServer",
           "ClientName": "ClientName"}
}

smbserver3 = {  # Microsoft-Windows-SMBServer/Connectivity
    1022: {"Descr": "File and printer sharing firewall rule enabled",
           "Provider": "Microsoft-Windows-SMBServer"}
}

smbserver4 = {  # Microsoft-Windows-SMBServer/Operational
    1023: {"Descr": "One or more shares present on this server have access based enumeration enabled",
           "Provider": "Microsoft-Windows-SMBServer"},

    1024: {"Descr": "SMB2 and SMB3 have been disabled on this server",
           "Provider": "Microsoft-Windows-SMBServer"},

    1025: {"Descr": "One or more named pipes or shares have been marked for access by anonymous users",
           "Provider": "Microsoft-Windows-SMBServer"}
}

smbserver5 = {  # Microsoft-Windows-SMBServer/Security
    551: {"Descr": "SMB session authentication failure",
          "Provider": "Microsoft-Windows-SMBServer",
          "SessionGUID": "SessionGuid",
          "ConnectionGUID": "ConnectionGuid",
          "Status": "Status",
          "TranslatedStatus": "TranslatedStatus",
          "ClientAddress": "ClientAddress",
          "SessionId": "SessionId",
          "UserName": "Username",
          "ClientName": "ClientName"},

    1006: {"Descr": "The share denied access to the client",
           "Provider": "Microsoft-Windows-SMBServer",
           "ShareName": "ShareName",
           "SharePath": "SharePath",
           "ClientAddress": "ClientAddress",
           "UserName": "Username",
           "ClientName": "ClientName",
           "MappedAccess": "MappedAccess",
           "GrantedAccess": "GrantedAccess",
           "ShareSecurityDescriptor": "ShareSecurityDescriptor",
           "Status": "Status",
           "TranslatedStatus": "TranslatedStatus",
           "SessionID": "SessionID"},

    1007: {"Descr": "The share denied anonymous access to the client",
           "Provider": "Microsoft-Windows-SMBServer",
           "ShareName": "ShareName",
           "SharePath": "SharePath",
           "ClientAddress": "ClientAddress",
           "ClientName": "ClientName"},

    1009: {"Descr": "The share denied anonymous access to the client",
           "Provider": "Microsoft-Windows-SMBServer",
           "ClientAddress": "ClientAddress",
           "ClientName": "ClientName",
           "SessionID": "SessionId",
           "SessionGUID": "SessionGuid",
           "ConnectionGUID": "ConnectionGuid"},

    1021: {"Descr": "LmCompatibilityLevel value is different from the default",
           "Provider": "Microsoft-Windows-SMBServer",
           "ConfiguredLmCompatibilityLevel": "+ConfiguredLmCompatibilityLevel",
           "DefaultLmCompatibilityLevel": "+DefaultLmCompatibilityLevel"}
}

storsvc = {  # Microsoft-Windows-Storsvc/Diagnostic
    1001: {"Descr": "NIL",
           "Provider": "Microsoft-Windows-Storsvc",
           "Version": "Version",
           "DiskNumber": "DiskNumber",
           "VendorId": "Vendor",
           "ProductRevision": "ProductRevision",
           "SerialNumber": "SerialNumber",
           "ParentId": "ParentId",
           "FileSystem": "FileSystem",
           "BusType": "+BusType",
           "PartitionStyle": "+PartitionStyle",
           "VolumeCount": "VolumeCount",
           "ContainsRawVolumes": "ContainsRawVolumes",
           "Size": "Capacity"},

    # Provider: Microsoft-Windows-Storsvc
    1002: {"Descr": "NIL",
           "Provider": "Microsoft-Windows-Storsvc",
           "Version": "Version",
           "Epoch": "Epoch",
           "DiskIndex": "DiskIndex",
           "TotalDisks": "TotalDisks",
           "DiskNumber": "DiskNumber",
           "VendorId": "Vendor",
           "ProductId": "Product",
           "ProductRevision": "ProductRevision",
           "SerialNumber": "SerialNumber",
           "ParentId": "ParentId",
           "FileSystem": "FileSystem",
           "BusType": "+BusType",
           "PartitionStyle": "+PartitionStyle",
           "VolumeCount": "VolumeCount",
           "ContainsRawVolumes": "ContainsRawVolumes",
           "Size": "Capacity"}
}

symantec = {  # Symantec Endpoint Protection Client
    51: {"Descr": "Detection Finish"}  # TODO
}

wdef = {  # Microsoft-Windows-Windows Defender/Operational
    1006: {"Descr": "<ProductName> has detected malware or other potentially unwanted software",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Detection ID": "DetectionId",
           "Detection Source": "Source",
           "Process Name": "ProcessPath",
           "Domain": "Domain",
           "User": "Username",
           "SID": "SID",
           "Threat ID": "ThreatId",
           "Threat Name": "Threat",
           "Severity Name": "Severity",
           "Category Name": "Category",
           "FWLink": "Link",
           "Path Found": "Path",
           "Detection Origin": "Origin",
           "Execution Status": "ExecutionStatus",
           "Detection Type": "Type",
           "Signature Version": "SignatureVersion",
           "Engine Version": "EngineVersion"},

    1007: {"Descr": "<ProductName> has taken action to protect this machine from malware or "
                    "other potentially unwanted software",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Detection ID": "DetectionId",
           "Status Description": "Status",
           "Domain": "Domain",
           "User": "Username",
           "SID": "SID",
           "Threat ID": "ThreatId",
           "Threat Name": "Threat",
           "Severity Name": "Severity",
           "Category Name": "Category",
           "FWLink": "Link",
           "Path": "Path",
           "Cleaning Action": "Cleaning Action",
           "Signature Version": "SignatureVersion",
           "Engine Version": "EngineVersion"},

    1008: {"Descr": "<ProductName> has encountered an error when taking action on malware or "
                    "other potentially unwanted software",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Detection ID": "DetectionId",
           "Status Description": "Status",
           "Domain": "Domain",
           "User": "Username",
           "SID": "SID",
           "Threat ID": "ThreatId",
           "Threat Name": "Threat",
           "Severity Name": "Severity",
           "Category Name": "Category",
           "FWLink": "Link",
           "Path": "Path",
           "Error Code": "ErrorCode",
           "Error Description": "Error",
           "Signature Version": "SignatureVersion",
           "Engine Version": "EngineVersion"},

    1009: {"Descr": "<ProductName> has restored an item from quarantine",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Domain": "Domain",
           "User": "Username",
           "SID": "SID",
           "Threat ID": "ThreatId",
           "Threat Name": "Threat",
           "Severity Name": "Severity",
           "Category Name": "Category",
           "FWLink": "Link",
           "Path": "Path",
           "Signature Version": "SignatureVersion",
           "Engine Version": "EngineVersion"},

    1010: {"Descr": "<ProductName> has encountered an error trying to restore an item from quarantine",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Error Code": "ErrorCode",
           "Error Description": "Error",
           "Domain": "Domain",
           "User": "Username",
           "SID": "SID",
           "Threat ID": "ThreatId",
           "Threat Name": "Threat",
           "Severity Name": "Severity",
           "Category Name": "Category",
           "FWLink": "Link",
           "Path": "Path",
           "Signature Version": "SignatureVersion",
           "Engine Version": "EngineVersion"},

    1011: {"Descr": "<ProductName> has deleted an item from quarantine",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Domain": "Domain",
           "User": "Username",
           "SID": "SID",
           "Threat ID": "ThreatId",
           "Threat Name": "Threat",
           "Severity Name": "Severity",
           "Category Name": "Category",
           "FWLink": "Link",
           "Path": "Path",
           "Signature Version": "SignatureVersion",
           "Engine Version": "EngineVersion"},

    1012: {"Descr": "<ProductName> has encountered an error trying to restore an item from quarantine",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Error Code": "ErrorCode",
           "Error Description": "Error",
           "Domain": "Domain",
           "User": "Username",
           "SID": "SID",
           "Threat ID": "ThreatId",
           "Threat Name": "Threat",
           "Severity Name": "Severity",
           "Category Name": "Category",
           "FWLink": "Link",
           "Path": "Path",
           "Signature Version": "SignatureVersion",
           "Engine Version": "EngineVersion"},

    1015: {"Descr": "<ProductName> has detected a suspicious behavior",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Detection ID": "DetectionId",
           "Detection Source": "Source",
           "Process Name": "ProcessPath",
           "Domain": "Domain",
           "User": "Username",
           "SID": "SID",
           "Threat ID": "ThreatId",
           "Threat Name": "Threat",
           "Severity Name": "Severity",
           "Category Name": "Category",
           "FWLink": "Link",
           "Path Found": "Path",
           "Detection Origin": "Origin",
           "Execution Status": "ExecutionStatus",
           "Detection Type": "Type",
           "Signature Version": "SignatureVersion",
           "Engine Version": "EngineVersion",
           "Process ID": "ProcessId",
           "Signature ID": "SignatureId",
           "FidelityValue": "FidelityValue",
           "FidelityLabel": "FidelityLabel",
           "Image File Hash": "ImageFileHash",
           "TargetFileName": "TargetFileName",
           "TargetFileHash": "TargetFileHash"},

    1116: {"Descr": "<ProductName> has detected malware or other potentially unwanted software",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Detection ID": "DetectionId",
           "Detection Time": "DetectionTime",
           "Threat Name": "Threat",
           "Severity Name": "Severity",
           "Category Name": "Category",
           "FWLink": "Link",
           "Status Description": "Status",
           "Source Name": "Source",
           "Process Name": "ProcessPath",
           "Detection User": "DetectionUser",
           "Path": "Path",
           "Origin Name": "Origin",
           "Execution Name": "Execution",
           "Type Name": "Type",
           "Action Name": "Action",
           "Error Code": "ErrorCode",
           "Error Description": "Error",
           "Post Clean Status": "PostCleanStatus",
           "Additional Actions String": "AdditionalActions",
           "Remediation User": "RemediationUser",
           "Signature Version": "SignatureVersion",
           "Engine Version": "EngineVersion"},

    1117: {"Descr": "<ProductName> has taken action to protect this machine from malware or "
                    "other potentially unwanted software",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Detection ID": "DetectionId",
           "Detection Time": "DetectionTime",
           "Threat Name": "Threat",
           "Severity Name": "Severity",
           "Category Name": "Category",
           "FWLink": "Link",
           "Status Description": "Status",
           "Source Name": "Source",
           "Process Name": "ProcessPath",
           "Detection User": "DetectionUser",
           "Path": "Path",
           "Origin Name": "Origin",
           "Execution Name": "Execution",
           "Type Name": "Type",
           "Action Name": "Action",
           "Error Code": "ErrorCode",
           "Error Description": "Error",
           "Post Clean Status": "PostCleanStatus",
           "Additional Actions String": "AdditionalActions",
           "Remediation User": "RemediationUser",
           "Signature Version": "SignatureVersion",
           "Engine Version": "EngineVersion"},

    1118: {"Descr": "<ProductName> has encountered a non-critical error when taking action on malware or "
                    "other potentially unwanted software",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Detection ID": "DetectionId",
           "Detection Time": "DetectionTime",
           "Threat Name": "Threat",
           "Severity Name": "Severity",
           "Category Name": "Category",
           "FWLink": "Link",
           "Status Description": "Status",
           "Source Name": "Source",
           "Process Name": "ProcessPath",
           "Detection User": "DetectionUser",
           "Path": "Path",
           "Origin Name": "Origin",
           "Execution Name": "Execution",
           "Type Name": "Type",
           "Action Name": "Action",
           "Error Code": "ErrorCode",
           "Error Description": "Error",
           "Post Clean Status": "PostCleanStatus",
           "Additional Actions String": "AdditionalActions",
           "Remediation User": "RemediationUser",
           "Signature Version": "SignatureVersion",
           "Engine Version": "EngineVersion"},

    1119: {"Descr": "<ProductName> has encountered a critical error when taking action on malware or "
                    "other potentially unwanted software",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Detection ID": "DetectionId",
           "Detection Time": "DetectionTime",
           "Threat Name": "Threat",
           "Severity Name": "Severity",
           "Category Name": "Category",
           "FWLink": "Link",
           "Status Description": "Status",
           "Source Name": "Source",
           "Process Name": "ProcessPath",
           "Detection User": "DetectionUser",
           "Path": "Path",
           "Origin Name": "Origin",
           "Execution Name": "Execution",
           "Type Name": "Type",
           "Action Name": "Action",
           "Error Code": "ErrorCode",
           "Error Description": "Error",
           "Post Clean Status": "PostCleanStatus",
           "Additional Actions String": "AdditionalActions",
           "Remediation User": "RemediationUser",
           "Signature Version": "SignatureVersion",
           "Engine Version": "EngineVersion"},

    1160: {"Descr": "<ProductName has detected potentially unwanted application (PUA)",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Detection ID": "DetectionId",
           "Detection Time": "DetectionTime",
           "Threat Name": "Threat",
           "Severity Name": "Severity",
           "Category Name": "Category",
           "FWLink": "Link",
           "Status Description": "Status",
           "Source Name": "Source",
           "Process Name": "ProcessPath",
           "Detection User": "DetectionUser",
           "Path": "Path",
           "Origin Name": "Origin",
           "Execution Name": "Execution",
           "Type Name": "Type",
           "Action Name": "Action",
           "Error Code": "ErrorCode",
           "Error Description": "Error",
           "Post Clean Status": "PostCleanStatus",
           "Additional Actions String": "AdditionalActions",
           "Remediation User": "RemediationUser",
           "Signature Version": "SignatureVersion",
           "Engine Version": "EngineVersion"},

    2050: {"Descr": "<ProductName> has uploaded a file for further analysis",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Filename": "FileName",
           "Sha256": "FileHash"},

    2051: {"Descr": "<ProductName> has encountered an error trying to upload a suspicious file for further analysis",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Filename": "FileName",
           "Sha256": "FileHash",
           "Signature Version": "SignatureVersion",
           "Engine Version": "EngineVersion",
           "Error Code": "ErrorCode"},

    5000: {"Descr": "<ProductName> Real-time Protection scanning for malware and "
                    "other potentially unwanted software was enabled",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion"},

    5001: {"Descr": "<ProductName> Real-time Protection scanning for malware and "
                    "other potentially unwanted software was disabled",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion"},

    5004: {"Descr": "<ProductName> Real-time Protection feature configuration has changed",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Feature Name": "Feature",
           "Feature ID": "FeatureId"},

    5007: {"Descr": "<ProductName> Configuration has changed. "
                    "If this is unexpected, you should review the settings as this may be the result of malware",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Old Value": "OldValue",
           "New Value": "NewValue"},

    5008: {"Descr": "<ProductName> engine has been terminated due to an unexpected error",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion",
           "Resource": "Resource",
           "Failure Type": "FailureType",
           "Exception Code": "ExceptionCode"},

    5009: {"Descr": "<ProductName> scanning for spyware and other potentially unwanted software has been enabled",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion"},

    5010: {"Descr": "<ProductName> scanning for spyware and other potentially unwanted software is disabled",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion"},

    5011: {"Descr": "<ProductName> scanning for viruses has been enabled",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion"},

    5012: {"Descr": "<ProductName> scanning for viruses is disabled",
           "Provider": "Microsoft-Windows-Windows Defender",
           "Product Name": "ProductName",
           "Product Version": "ProductVersion"}
}

winrm = {  # Microsoft-Windows-WinRM/Operational
    6: {"Descr": "Creating WSMan session. The connection string is <Connection>",
        "Provider": "Microsoft-Windows-WinRM",
        "connection": "Connection"},

    8: {"Descr": "Closing WSMan session",
        "Provider": "Microsoft-Windows-WinRM"},  # empty

    15: {"Descr": "Closing WSMan command",
         "Provider": "Microsoft-Windows-WinRM"},  # empty

    16: {"Descr": "Closing WSMan shell",
         "Provider": "Microsoft-Windows-WinRM"},  # empty

    33: {"Descr": "Closing WSMan session completed successfully",
         "Provider": "Microsoft-Windows-WinRM"},  # empty

    91: {"Descr": "Creating WSMan shell on server with <ResourceUri>",
         "Provider": "Microsoft-Windows-WinRM",
         "resourceUri": "ResourceUri",
         "shellId": "ShellId"},

    169: {"Descr": "<TargetUsername> authenticated successfully using <AuthMechanism>",  # Win7 only?
          "Provider": "Microsoft-Windows-WinRM",
          "username": "TargetUsername",
          "authenticationMechanism": "AuthMechanism"}
}

wlan = {  # Microsoft-Windows-WLAN-AutoConfig/Operational
    8001: {"Descr": "WLAN AutoConfig service has successfully connected to a wireless network",
           "Provider": "Microsoft-Windows-WLAN-AutoConfig",
           "InterfaceGuid": "InterfaceGuid",
           "InterfaceDescription": "InterfaceDescr",
           "ConnectionMode": "ConnectionMode",
           "ProfileName": "ProfileName",
           "SSID": "SSID",
           "BSSType": "BSSType",
           "PHYType": "PHYType",
           "AuthenticationAlgorithm": "AuthAlgo",
           "CipherAlgorithm": "CipherAlgo",
           "OnexEnabled": "IsOnexEnabled",
           "ConnectionId": "ConnectionId",
           "NonBroadcast": "IsNonBroadcast"},

    8002: {"Descr": "WLAN AutoConfig service failed to connect to a wireless network",
           "Provider": "Microsoft-Windows-WLAN-AutoConfig",
           "InterfaceGuid": "InterfaceGuid",
           "InterfaceDescription": "InterfaceDescr",
           "ConnectionMode": "ConnectionMode",
           "ProfileName": "ProfileName",
           "SSID": "SSID",
           "BSSType": "BSSType",
           "FailureReason": "FailureReason",
           "ReasonCode": "ReasonCode",
           "ConnectionId": "ConnectionId",
           "RSSI": "RSSI"},

    8003: {"Descr": "WLAN AutoConfig service has successfully disconnected from a wireless network",
           "Provider": "Microsoft-Windows-WLAN-AutoConfig",
           "InterfaceGuid": "InterfaceGuid",
           "InterfaceDescription": "InterfaceDescr",
           "ConnectionMode": "ConnectionMode",
           "ProfileName": "ProfileName",
           "SSID": "SSID",
           "BSSType": "BSSType",
           "Reason": "Reason",
           "ConnectionId": "ConnectionId",
           "ReasonCode": "ReasonCode"},

    11000: {"Descr": "Wireless network association started",
            "Provider": "Microsoft-Windows-WLAN-AutoConfig",
            "DeviceGuid": "InterfaceGuid",
            "Adapter": "InterfaceDescr",
            "LocalMac": "LocalMac",
            "SSID": "SSID",
            "BSSType": "BSSType",
            "Auth": "AuthAlgo",
            "Cipher": "CipherAlgo",
            "OnexEnabled": "IsOnexEnabled",
            "ConnectionId": "ConnectionId",
            "IhvConnectivitySetting": "IhvConnectivitySetting"}
}

wmi = {  # Microsoft-Windows-WMI-Activity/Operational (Win8+)
    5857: {"Descr": "<ProviderName> started with <ResultCode>",  # wmiprvse execution
           "ProviderName": "ProviderName",
           "Code": "ResultCode",
           "HostProcess": "ProcessName",
           "ProcessID": "ProcessID",
           "ProviderPath": "ProviderPath"},

    5860: {"Descr": "Registration of temporary event consumer",  # Win10 v1511+
           "Provider": "Microsoft-Windows-WMI-Activity",
           "NamespaceName": "Namespace",
           "Query": "Query",
           "User": "Username",
           "processid": "ProcessId",  # < Win10 v1803
           "Processid": "ProcessId",  # Win10 v1803+
           "MachineName": "Hostname",  # < Win10 v1803
           "ClientMachine": "Hostname",  # Win10 v1803+
           "PossibleCause": "PossibleCause"},

    5861: {"Descr": "Registration of permanent event consumer",  # Win10 v1607+
           "Provider": "Microsoft-Windows-WMI-Activity",
           "Namespace": "Namespace",
           "ESS": "ESS",
           "CONSUMER": "Consumer",
           "PossibleCause": "PossibleCause"}
}
